version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ollama
    ports:
      - "8000:8000"
      - "5678:5678" # Debug port for VS Code or debugpy

  ui:
    build:
      context: ./ui
    command: npm run dev -- --host
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=http://backend:8000

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    ports:
      - "11434:11434"

volumes:
  ollama_data:

# Ollama is now managed by Docker Compose.
# Backend connects to Ollama at http://ollama:11434
